Repository team-azito/next-netflix-19th, pull requests merged in 2024-05, with the labels that each got.

#2 [#1] 프로젝트 초기 설정, axios 설정, tailwind css 설정, 라우팅 구조 잡기
  .eslintrc.json
  package-lock.json
  package.json
  public/fonts/.gitkeep
  public/icons/home/.gitkeep
  public/icons/media/.gitkeep
  public/icons/search/.gitkeep
  public/images/.gitkeep
  public/next.svg
  public/vercel.svg
  src/api/axiosInstance.ts
  src/api/home.ts
  src/app/favicon.ico
  src/app/globals.css
  src/app/home/page.tsx
  src/app/media/[id]/page.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/types/svgr.d.ts
  tailwind.config.ts
Labels: 🐠 Chore

#4 [#3] 랜딩페이지(/) 구현
  .prettierrc
  package-lock.json
  package.json
  public/animation/lottie-netflix.json
  src/app/globals.css
  src/app/home/page.tsx
  src/app/icon.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/root/LandingAnimation.tsx
  tsconfig.json
Labels: 🐷 Feat

#21 [#20] 검색 페이지 구현
  .prettierrc.json
  package-lock.json
  package.json
  public/icons/home/.gitkeep
  public/icons/search/.gitkeep
  public/icons/search/icon-close.svg
  public/icons/search/icon-noImage.svg
  public/icons/search/icon-play.svg
  public/icons/search/icon-search.svg
  public/images/sample.png
  src/api/axiosInstance.ts
  src/api/home.ts
  src/api/search.ts
  src/app/ReactQueryProvider.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/more/page.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/home/MovieSection.tsx
  src/components/search/SearchMovies.tsx
  src/components/search/SearchedMovies.tsx
  src/components/search/SkeletonMovies.tsx
  src/hooks/.gitkeep
  src/hooks/useInfiniteScroll.ts
  src/types/search.ts
  tailwind.config.ts
Labels: 🐷 Feat

#27 [#26] 상세 페이지 관련 코드 리뷰 반영 완료
  src/api/media.ts
  src/app/media/[id]/page.tsx
  src/components/common/BottomNavbarItem.tsx
  src/components/home/MoviePlay.tsx
  src/components/search/SearchedMovies.tsx
  src/types/media.ts
Labels: 🐸 Refactor
